### ISSUE TITLE
Ingame Errormessage

### ISSUE THREAD

**Issue by Garti** [sba5827/StriLi#10]
I get an error message right when I log in. StrLi is the only activated addon, except one for the error messages:

> Date: 2022-06-29 18:53:59
> ID: 1
> Error occured in: Global
> Count: 2
> Message: ..\AddOns\StriLi\Core.lua line 899:
>    bad argument #1 to 'pairs' (table expected, got nil)
> Debug:
>    (tail call): ?
>    [C]: pairs()
>    StriLi\Core.lua:899: StriLi_RefreshUI()
>    StriLi\Core.lua:890: StriLi_MainFrame_OnLoad()
>    StriLi\Core.lua:93:
>       StriLi\Core.lua:83
>    (tail call): ?
>    [C]: ?
>    [string "safecall Dispatcher[1]"]:9:
>       [string "safecall Dispatcher[1]"]:5
>    (tail call): ?
>    ...ace\AddOns\StriLi\Libs\AceAddon-3.0\AceAddon-3.0.lua:510: InitializeAddon()
>    ...ace\AddOns\StriLi\Libs\AceAddon-3.0\AceAddon-3.0.lua:622:
>       ...ace\AddOns\StriLi\Libs\AceAddon-3.0\AceAddon-3.0.lua:615

**Comment by sba5827** [comment]
Thanks for the report. Fix will be in the next release. Workaround until release: Join a raid once then the error will not occur anymore because the corresponding variable is always initialized via SavedVariables.
