### ISSUE TITLE
RaidMembersDB not initialized?!

### ISSUE THREAD

**Issue by daniel-w-f** [sba5827/StriLi#27]
I tried to use the addon for the first time. I am in a raid, I am the raidleader and I am the master looter.
Using `/sl 5 <link to item>` is starting 

```text
[16:44:58] [RW] [xyz]: Es wird um das Item [Veheerende Sabatons] gewürfelt. Du hast 5 Sekunden zeit. 
[16:45:00] [RW] [xyz]: 3 
[16:45:01] xyz würfelt. Ergebnis: 95 (1-100) 
[16:45:01] [RW] [xyz]: 2 
[16:45:02] [RW] [xyz]: 1 
[16:45:02] xyz würfelt. Ergebnis: 26 (1-99) 
[16:45:03] [RW] [xyz]: --- 
[16:45:03] [R] [xyz]: ---Main--- 
[16:45:03] [R] [xyz]: ---Sec---
```

Getting this Lua error

```lua
1x StriLi\RaidMembersDB.lua:62: Raidmember xyz does not exist in DB.
[string "=[C]"]: in function `error'
[string "@StriLi\RaidMembersDB.lua"]:62: in function `get'
[string "@StriLi\AutoRollAnalyser.lua"]:134: in function `registerRoll'
[string "@StriLi\AutoRollAnalyser.lua"]:118: in function `On_CHAT_MSG_SYSTEM'
[string "@StriLi\AutoRollAnalyser.lua"]:66: in function `chatMsgSystem_cbFnc'
[string "@StriLi\EventHandler.lua"]:54: in function `OnEvent'
[string "@StriLi\EventHandler.lua"]:27: in function <StriLi\EventHandler.lua:26>

Locals:
(*temporary) = "Raidmember xyz does not exist in DB."
```

Is there any command (that is currently not documented?) to initialize the whole addon? Should the RaidMembersDB be initialized automatically?
Do I have to be in a raid instance for that?

**Comment by sba5827** [comment]
This problem should not occur unless you have manually deleted a member from the list or you have the "Unkown Bug" where all players are shown as unknown. In both cases I cannot fix the problem. Except to no longer allow active raid participants to be removed from the list.

The RaidmemberDB is initialized and updated automatically. No additional command is necessary.

On which patch level are you playing and on which server? Maybe the problem is also here.

**Comment by daniel-w-f** [comment]
WoW WotLK Version 3.4.0 (46368), the current live version of WoW Classic. EU - Everlook.
And version/tag 3.00 from the addon.
I have never deleted manually any member as the GUI has never shown any member to me. I also haven't seen any one as unkown.
I was a bit to busy tonight to give the addon a try during our raid. So far I have only tested it in a raid group with 2 people in Dalaran.

**Comment by sba5827** [comment]
The addon is based on the wotlk releas of 2008. This is why you're encountering the errors.
