### ISSUE TITLE
Question: Will there be a 3.4.0 version?

### ISSUE THREAD

**Issue by daniel-w-f** [sba5827/StriLi#30]
The readme is saying that this addon is for `WoW version 3.3.5a WotLK`. But recently there were some updates on the addon. 
Is the addon getting updated for version 3.4.0?

I haven't seen it working so far yet, but according to the description, it seems to be exactly what I am looking for.
If there will not be an official update to the addon, would it be okay if I try to get a fork updated to 3.4.0?

Some updates seem to be necessary as e.g. event "PARTY_MEMBERS_CHANGED" is no longer supported by the WoW API ("GROUP_ROSTER_UPDATE", has to be used).

**Comment by sba5827** [comment]
Feel free to fork and port this addon to WotlK-Classic version. I am not planning on doing this right now. This addon is used on private servers running on the 2008 version.
