### ISSUE TITLE
Ignore group 6-8

### ISSUE THREAD

**Issue by Garti** [sba5827/StriLi#42]
It would be nice if there was an option to ignore groups 6-8.

There are raids where these groups are used for benched players. Displaying these player unfortunately makes the list very long. For the sake of clarity and because these players usually do not collect loot anyway, a display is unnecessary and should be optional.

**Comment by sba5827** [comment]
Solved in Version [3.12](https://github.com/sba5827/StriLi/releases/tag/3.12)


![image](https://user-images.githubusercontent.com/38493688/236537068-84b3fbcb-407e-4b69-bc47-d178b58e654f.png)
